version: '3'

services:
  site:
    image: jekyll/jekyll
    command: jekyll serve --livereload --verbose
    expose:
      - 4000
    volumes:
      - ../..:/srv/jekyll
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - site
    ports:
     - "4001:4001"